/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V2IndexRouteImport } from './routes/v2/index'
import { Route as V2ServicesRouteImport } from './routes/v2/services'
import { Route as V2ContactRouteImport } from './routes/v2/contact'
import { Route as V2AboutRouteImport } from './routes/v2/about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2IndexRoute = V2IndexRouteImport.update({
  id: '/v2/',
  path: '/v2/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2ServicesRoute = V2ServicesRouteImport.update({
  id: '/v2/services',
  path: '/v2/services',
  getParentRoute: () => rootRouteImport,
} as any)
const V2ContactRoute = V2ContactRouteImport.update({
  id: '/v2/contact',
  path: '/v2/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const V2AboutRoute = V2AboutRouteImport.update({
  id: '/v2/about',
  path: '/v2/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v2/about': typeof V2AboutRoute
  '/v2/contact': typeof V2ContactRoute
  '/v2/services': typeof V2ServicesRoute
  '/v2/': typeof V2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v2/about': typeof V2AboutRoute
  '/v2/contact': typeof V2ContactRoute
  '/v2/services': typeof V2ServicesRoute
  '/v2': typeof V2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v2/about': typeof V2AboutRoute
  '/v2/contact': typeof V2ContactRoute
  '/v2/services': typeof V2ServicesRoute
  '/v2/': typeof V2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/v2/about'
    | '/v2/contact'
    | '/v2/services'
    | '/v2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/v2/about'
    | '/v2/contact'
    | '/v2/services'
    | '/v2'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/v2/about'
    | '/v2/contact'
    | '/v2/services'
    | '/v2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  V2AboutRoute: typeof V2AboutRoute
  V2ContactRoute: typeof V2ContactRoute
  V2ServicesRoute: typeof V2ServicesRoute
  V2IndexRoute: typeof V2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/': {
      id: '/v2/'
      path: '/v2'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/services': {
      id: '/v2/services'
      path: '/v2/services'
      fullPath: '/v2/services'
      preLoaderRoute: typeof V2ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/contact': {
      id: '/v2/contact'
      path: '/v2/contact'
      fullPath: '/v2/contact'
      preLoaderRoute: typeof V2ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/about': {
      id: '/v2/about'
      path: '/v2/about'
      fullPath: '/v2/about'
      preLoaderRoute: typeof V2AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  V2AboutRoute: V2AboutRoute,
  V2ContactRoute: V2ContactRoute,
  V2ServicesRoute: V2ServicesRoute,
  V2IndexRoute: V2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
